# M365 SMTP Relay
name: m365-relay
services:
  smtp:
    build: .
    environment:
      SYSTEM_TIMEZONE: "Australia/Sydney"
      MYNETWORKS: "10.0.0.0/8 127.0.0.0/8 172.16.0.0/12 192.168.0.0/16"
      EMAIL: "user@domain.com"
      EMAILPASS: "the-password1234"
      FROMADDRESSMASQ: 0      
    restart: unless-stopped
    ports:
      - "8025:25"
